-- qnViewPort: monitor layout.
-- Reads qnViewPortMonitors from Monitors.lua (generated by scripts\Initialize-WowMonitors.ps1
-- or Set-WowWindow.ps1) and derives from it
--   * the main monitor: viewport of the 3D world and area for UIParent,
--   * the parts of the window that are visible on a monitor,
--   * the 2nd monitor and the selectable monitors for the placement areas (SecondScreen.lua).
-- Also: constrain UIParent to the main monitor, find frames outside the monitors.
-- It provides the visible area to qnCore.Visible (bring frames into the visible area, also for
-- qnThreatMeter, qnNumKeyPad, qnBuffMod) and reports every layout change there.
-- Rectangles in window pixels { x, y, w, h }, origin top left. "abs" = units at
-- effective scale 1, origin bottom left (like GetLeft() * GetEffectiveScale()).

local _, ns = ...
local L = ns.L
local Visible = qnCore.Visible

local Layout = {}
ns.Layout = Layout

local DB = ns.DualDB

---------------------------------------------------------------------------
-- Monitor data
---------------------------------------------------------------------------

local cache, cacheW, cacheH, problem

-- Monitor data converted to the current window size; nil if none or not matching.
function Layout.GetData()
	local W, H = ns.screen[1], ns.screen[2]
	if cacheW == W and cacheH == H then
		return cache or nil
	end
	cacheW, cacheH, cache, problem = W, H, false, nil

	local data = _G.qnViewPortMonitors
	if type(data) ~= "table" or type(data.window) ~= "table" or type(data.monitors) ~= "table" then
		problem = L["No monitor data – run qnViewPort\\scripts\\Initialize-WowMonitors.ps1, then /reload."]
		return nil
	end
	local dw, dh = tonumber(data.window.width) or 0, tonumber(data.window.height) or 0
	if dw <= 0 or dh <= 0 then
		problem = L["Monitor data without window size."]
		return nil
	end
	-- Convert a differently sized window (e.g. resolution scale) only if the aspect ratio is the same.
	if math.abs(dw / dh - W / H) > 0.01 then
		problem = L["Game window %d × %d does not match the monitor data (%d × %d) – run Set-WowWindow.ps1."]:format(W, H, dw, dh)
		return nil
	end
	local kx, ky = W / dw, H / dh
	local function Px(v, k)
		return math.floor((tonumber(v) or 0) * k + 0.5)
	end
	local list, main = {}, nil
	for _, m in ipairs(data.monitors) do
		local r = {
			index = #list + 1,
			x = Px(m.x, kx), y = Px(m.y, ky), w = Px(m.width, kx), h = Px(m.height, ky),
			name = m.name, device = m.device, selected = m.selected,
		}
		if r.w > 0 and r.h > 0 then
			list[#list + 1] = r
			if m.main and not main then
				main = r
			end
		end
	end
	main = main or list[1]
	if not main then
		problem = L["Monitor data without a monitor."]
		return nil
	end
	cache = { monitors = list, main = main }
	return cache
end

-- Monitor data, if it is to be used
function Layout.Active()
	return DB().useMonitorData and Layout.GetData() or nil
end

function Layout.GetProblem()
	Layout.GetData()
	return problem
end

-- whole game window
function Layout.Full()
	return { x = 0, y = 0, w = ns.screen[1], h = ns.screen[2] }
end

local function IsFull(r)
	return r.x < 1 and r.y < 1 and r.w > ns.screen[1] - 1 and r.h > ns.screen[2] - 1
end

-- Rectangle of the 2nd monitor from the manual settings (x, y, w, h)
local function ManualSecond()
	local d = DB()
	local W, H = ns.screen[1], ns.screen[2]
	local w2 = math.max(1, math.min(math.floor(d.width), W - 1))
	local h2 = math.max(1, math.min(math.floor(d.height), H))
	local oy = math.max(0, math.min(math.floor(d.offsetY), H - h2))
	return { x = (d.side == "LEFT") and 0 or (W - w2), y = oy, w = w2, h = h2 }
end

-- Main monitor on which the 3D world lies; nil = whole window
function Layout.GetMainRect()
	local data = Layout.Active()
	if data then
		return data.main
	end
	if DB().enabled then
		local s = ManualSecond()
		local W, H = ns.screen[1], ns.screen[2]
		return { x = (DB().side == "LEFT") and s.w or 0, y = 0, w = W - s.w, h = H }
	end
end

-- 2nd monitor: largest non-main monitor from the monitor data, otherwise from the manual settings
function Layout.GetSecondRect()
	local data = Layout.Active()
	if not data then
		return ManualSecond()
	end
	local best
	for _, r in ipairs(data.monitors) do
		if r ~= data.main and (not best or r.w * r.h > best.w * best.h) then
			best = r
		end
	end
	return best
end

-- Parts of the window that are visible on a monitor (window pixels)
function Layout.GetVisible()
	local data = Layout.Active()
	if data then
		return data.monitors
	end
	if DB().enabled then
		return { Layout.GetMainRect(), ManualSecond() }
	end
	return { Layout.Full() }
end

-- Viewport offsets { left, right, top, bottom } for a rectangle
function Layout.ViewportFor(r)
	local W, H = ns.screen[1], ns.screen[2]
	return { r.x, W - r.x - r.w, r.y, H - r.y - r.h }
end

function Layout.ToAbs(r)
	local ux, uy = ns.UnitsPerPixel()
	local H = ns.screen[2]
	return { l = r.x * ux, r = (r.x + r.w) * ux, t = (H - r.y) * uy, b = (H - r.y - r.h) * uy }
end

function Layout.GetVisibleAbs()
	local out = {}
	for i, r in ipairs(Layout.GetVisible()) do
		out[i] = Layout.ToAbs(r)
	end
	return out
end

---------------------------------------------------------------------------
-- Constrain UIParent to the main monitor
-- Blizzard's interface hangs almost entirely on UIParent (corners, center). If UIParent
-- only covers the main monitor, the interface ends up there – even with monitors of different sizes,
-- where parts of the window are not visible on any monitor.
---------------------------------------------------------------------------

-- Only on button press (options, "Monitors" page): this moves all Blizzard frames attached to
-- UIParent. Lasts until reset, turning off dual monitor mode, a profile
-- without dual monitor mode or /reload. Until then ReapplyUI maintains the chosen constraint.
local constrained = false
local constrainedRect   -- area applied last (pixels), while constrained

-- rect = area in pixels or nil = whole window. Returns true if applied.
local function SetUIParent(rect)
	if InCombatLockdown() then
		ns.Print(L["%s is protected – cannot be moved in combat."]:format("UIParent"))
		return false
	end
	-- ns.FrameSetPoint = method of the widget class (bypassing overridden methods)
	local W, H = ns.screen[1], ns.screen[2]
	local ux, uy = ns.UnitsPerPixel()
	local s = UIParent:GetScale()
	ns.FrameClearAllPoints(UIParent)
	if rect then
		-- UIParent has no parent: offsets in its own units, relative to the window
		ns.FrameSetPoint(UIParent, "TOPLEFT", rect.x * ux / s, -rect.y * uy / s)
		ns.FrameSetPoint(UIParent, "BOTTOMRIGHT", -(W - rect.x - rect.w) * ux / s, (H - rect.y - rect.h) * uy / s)
	else
		ns.FrameSetPoint(UIParent, "TOPLEFT", 0, 0)
		ns.FrameSetPoint(UIParent, "BOTTOMRIGHT", 0, 0)
	end
	constrained = rect ~= nil
	constrainedRect = rect
	Visible.Notify()
	return true
end

-- Reapplies the explicitly chosen constraint: Blizzard resets UIParent on every
-- PLAYER_ENTERING_WORLD (UpdateUIParentPosition, UIParentUtil.lua), and the offsets in
-- UIParent units depend on window size and scale (ns.ApplyGeometry). In combat only
-- afterwards. No recursion: SetUIParent sets via ns.FrameSetPoint, not via Blizzard's function.
local function ReapplyUI()
	if not constrained or qnCore.DeferInCombat(ReapplyUI) then
		return
	end
	-- determine the area anew (the window size may have changed), otherwise use the remembered one
	local rect = DB().enabled and Layout.GetMainRect()
	if not rect or IsFull(rect) then
		rect = constrainedRect
	end
	SetUIParent(rect)
end
Layout.ReapplyUI = ReapplyUI

-- "Interface to main monitor" button ("Monitors" page)
function Layout.ConstrainUI()
	local rect = DB().enabled and Layout.GetMainRect()
	if not rect or IsFull(rect) then
		ns.Print(L["Only in dual monitor mode, when the game window spans several monitors."])
		return
	end
	if SetUIParent(rect) then
		ns.Print(L["Blizzard interface on the main monitor (until reset or /reload)."])
	end
end

-- "Reset" button or dual monitor mode off: across the whole window again
function Layout.ReleaseUI()
	if constrained then
		SetUIParent(nil)
	end
end

function Layout.IsUIConstrained()
	return constrained
end

---------------------------------------------------------------------------
-- Visibility of frames (computing and moving: qnCore.Visible)
---------------------------------------------------------------------------

local function FrameName(f)
	return f:GetName() or f:GetDebugName()
end

-- Origin: Blizzard if the global name was created by Blizzard's (secure) code.
local function Source(f)
	local name = f:GetName()
	if name and _G[name] == f and issecurevariable then
		local secure, addon = issecurevariable(_G, name)
		if secure then
			return "Blizzard", true
		end
		return addon or "Addon", false
	end
	return L["unnamed"], false
end

-- Checks all visible interface elements (children of UIParent) and returns those that are fully
-- or partly outside the monitors, Blizzard first. Moves nothing.
function Layout.CheckFrames()
	local rects = Layout.GetVisibleAbs()
	local ui = Visible.FrameAbs(UIParent)
	local result = {}
	for _, f in ipairs({ UIParent:GetChildren() }) do
		if not f:IsForbidden() and not f.qnViewPortIgnore
			and f:IsVisible() and f:GetAlpha() > 0.05 then
			local a = Visible.FrameAbs(f)
			local fullscreen = a and ui and math.abs(a.l - ui.l) < 2 and math.abs(a.r - ui.r) < 2
				and math.abs(a.t - ui.t) < 2 and math.abs(a.b - ui.b) < 2
			if a and not fullscreen and a.r - a.l > 4 and a.t - a.b > 4 then
				local visible = Visible.VisibleFraction(a, rects)
				if visible <= 0.9999 then
					local source, blizzard = Source(f)
					result[#result + 1] = {
						frame = f, name = FrameName(f), source = source, blizzard = blizzard,
						visible = visible, editMode = f.system ~= nil, protected = f:IsProtected(),
					}
				end
			end
		end
	end
	table.sort(result, function(x, y)
		if x.blizzard ~= y.blizzard then
			return x.blizzard
		end
		return x.name < y.name
	end)
	return result
end

-- Moves ONE element into the visible area (button in the options list).
-- Chat frames: save the position via Blizzard's function, otherwise the chat resets it on load.
function Layout.MoveFrame(f)
	local name = FrameName(f)
	local moved = Visible.MoveAndReport(f, name, ns.Print)
	if moved then
		if name:match("^ChatFrame%d+$") then
			FCF_SavePositionAndDimensions(f)
		end
		if f.system ~= nil then
			ns.Print(L["Edit Mode frame: lasts until /reload or until the layout is reloaded. To keep it: move it in Edit Mode."])
		end
	end
	return moved
end

---------------------------------------------------------------------------
-- Tooltips at the monitor edge (Titan plugins in Titan.lua, bag slots in SecondScreen.lua)
-- Blizzard and Titan choose a tooltip's side by GetScreenWidth() or UIParent, i.e.
-- by the whole game window. At the edge of a monitor the tooltip then reaches into a part of the
-- window that is not visible on any monitor, or onto the neighboring monitor.
---------------------------------------------------------------------------

-- Monitor (abs rectangle) containing the center of frame; nil = none
function Layout.MonitorAt(frame)
	local a = Visible.FrameAbs(frame)
	if not a then
		return nil
	end
	local x, y = (a.l + a.r) / 2, (a.t + a.b) / 2
	for _, r in ipairs(Layout.GetVisibleAbs()) do
		if x >= r.l and x <= r.r and y >= r.b and y <= r.t then
			return r
		end
	end
end

-- Re-anchors tip to owner if it is anchored there and extends beyond owner's monitor.
-- The current side stays if it fits; otherwise the other side, and whatever still
-- sticks out is pushed inside. If it fits, the anchor stays unchanged (Titan's control frames
-- hang on the center of the plugin edge, e.g. TOPLEFT to BOTTOM – re-anchored at a corner they would jump).
function Layout.FitToMonitor(tip, owner)
	if not (tip and owner and tip:IsShown()) then
		return
	end
	local point, rel, relPoint, ox, oy = tip:GetPoint(1)
	if rel ~= owner or type(point) ~= "string" then
		return
	end
	local area, b = Layout.MonitorAt(owner), Visible.FrameAbs(owner)
	local s = tip:GetEffectiveScale()
	local w, h = (tip:GetWidth() or 0) * s, (tip:GetHeight() or 0) * s
	if not (area and b and w > 0 and h > 0) then
		return
	end

	-- Position with the current anchor; if nothing sticks out, change nothing
	relPoint = type(relPoint) == "string" and relPoint or point
	local ax = (relPoint:find("LEFT$") and b.l) or (relPoint:find("RIGHT$") and b.r) or (b.l + b.r) / 2
	local ay = (relPoint:find("^TOP") and b.t) or (relPoint:find("^BOTTOM") and b.b) or (b.t + b.b) / 2
	ax, ay = ax + (tonumber(ox) or 0) * s, ay + (tonumber(oy) or 0) * s
	local l0 = (point:find("LEFT$") and ax) or (point:find("RIGHT$") and ax - w) or ax - w / 2
	local t0 = (point:find("^TOP") and ay) or (point:find("^BOTTOM") and ay + h) or ay + h / 2
	local e = 0.5   -- rounding
	if l0 >= area.l - e and l0 + w <= area.r + e and t0 <= area.t + e and t0 - h >= area.b - e then
		return
	end

	-- vertical: TOP = below owner, BOTTOM = above
	local v = point:find("^BOTTOM") and "BOTTOM" or "TOP"
	local below, above = b.b - h >= area.b, b.t + h <= area.t
	if v == "TOP" and not below and above then
		v = "BOTTOM"
	elseif v == "BOTTOM" and not above and below then
		v = "TOP"
	end
	-- horizontal: LEFT = extends to the right, RIGHT = to the left
	local hz = point:find("RIGHT$") and "RIGHT" or "LEFT"
	local toRight, toLeft = b.l + w <= area.r, b.r - w >= area.l
	if hz == "LEFT" and not toRight and toLeft then
		hz = "RIGHT"
	elseif hz == "RIGHT" and not toLeft and toRight then
		hz = "LEFT"
	end

	-- push whatever still sticks out into the monitor
	local left = hz == "LEFT" and b.l or (b.r - w)
	local top = v == "TOP" and b.b or (b.t + h)
	local dx, dy = 0, 0
	if left + w > area.r then
		dx = area.r - (left + w)
	end
	if left + dx < area.l then
		dx = area.l - left
	end
	if top - h < area.b then
		dy = area.b - (top - h)
	end
	if top + dy > area.t then
		dy = area.t - top
	end

	tip:ClearAllPoints()
	tip:SetPoint(v .. hz, owner, (v == "TOP" and "BOTTOM" or "TOP") .. hz, dx / s, dy / s)
end

-- Side on which the comparison tooltips hang on tip: true = right, false = left, nil = unknown.
-- Blizzard: RIGHT to LEFT or LEFT to RIGHT of tip; here: TOPRIGHT to TOPLEFT or TOPLEFT to TOPRIGHT.
local function CompareSide(tip, shown)
	for _, t in ipairs(shown) do
		for i = 1, t:GetNumPoints() do
			local _, rel, relPoint = t:GetPoint(i)
			if rel == tip and type(relPoint) == "string" then
				if relPoint:find("RIGHT$") then
					return true
				elseif relPoint:find("LEFT$") then
					return false
				end
			end
		end
	end
end

-- Comparison tooltips (tip.shoppingTooltips) next to tip on its monitor.
-- Blizzard (TooltipComparisonManager:AnchorShoppingTooltips) chooses the side by GetScreenWidth()
-- and attaches the tooltips with TOP to tip. If Blizzard's side fits on the monitor it stays – otherwise
-- Blizzard's choice and this one would alternate on every refresh (flicker). Otherwise the side
-- with enough room, if necessary the one with more room; if they stick out at the bottom, they are pushed up.
function Layout.FitCompareToMonitor(tip)
	local list = tip and tip.shoppingTooltips
	local primary, secondary = list and list[1], list and list[2]
	if not (primary and primary:IsShown()) then
		return
	end
	local area, g = Layout.MonitorAt(tip), Visible.FrameAbs(tip)
	if not (area and g) then
		return
	end
	local shown = { primary }
	if secondary and secondary:IsShown() then
		shown[2] = secondary
	end
	local width, height = 0, 0
	for _, t in ipairs(shown) do
		local s = t:GetEffectiveScale()
		width = width + (t:GetWidth() or 0) * s
		height = math.max(height, (t:GetHeight() or 0) * s)
	end
	if width <= 0 then
		return
	end
	local roomRight, roomLeft = area.r - g.r, g.l - area.l
	local current = CompareSide(tip, shown)
	local right
	if current == true and roomRight >= width or current == false and roomLeft >= width then
		right = current
	elseif roomRight >= width then
		right = true
	elseif roomLeft >= width then
		right = false
	else
		right = roomRight >= roomLeft
	end
	local dy = 0
	if g.t - height < area.b then
		dy = math.min(area.b - (g.t - height), area.t - g.t)
	end
	if right == current and dy == 0 then
		return   -- Blizzard's position fits
	end

	-- the first attaches to tip, the second next to it (order as in Blizzard's code)
	local s = primary:GetEffectiveScale()
	primary:ClearAllPoints()
	if secondary then
		secondary:ClearAllPoints()
	end
	if #shown == 1 then
		primary:SetPoint(right and "TOPLEFT" or "TOPRIGHT", tip, right and "TOPRIGHT" or "TOPLEFT", 0, dy / s)
	elseif right then
		secondary:SetPoint("TOPLEFT", tip, "TOPRIGHT", 0, dy / secondary:GetEffectiveScale())
		primary:SetPoint("TOPLEFT", secondary, "TOPRIGHT")
	else
		primary:SetPoint("TOPRIGHT", tip, "TOPLEFT", 0, dy / s)
		secondary:SetPoint("TOPRIGHT", primary, "TOPLEFT")
	end
end

---------------------------------------------------------------------------
-- Apply layout (start, window size changed)
---------------------------------------------------------------------------

local function Key(data)
	local parts = { ns.screen[1] .. "x" .. ns.screen[2] }
	for _, m in ipairs(data.monitors) do
		parts[#parts + 1] = ("%d,%d,%d,%d%s"):format(m.x, m.y, m.w, m.h, m == data.main and "*" or "")
	end
	return table.concat(parts, ";")
end

-- New monitor layout: put the 3D world (viewport) on the main monitor once.
-- Neither turns on dual monitor mode nor moves interface elements.
-- Later changes by the player to the viewport stay until the layout changes.
function Layout.Refresh()
	local data = Layout.Active()
	if data and #data.monitors > 1 and not IsFull(data.main) then
		local key = Key(data)
		local g = ns.global
		if key ~= g.layoutKey then
			-- saved account-wide: applied once per layout, not once per profile
			g.layoutKey = key
			ns.EndKeep()
			ns.ApplyViewport(Layout.ViewportFor(data.main))
			ns.Print(L["Monitor layout applied: %d monitors, 3D world on the main monitor (%d × %d)."]:format(
				#data.monitors, data.main.w, data.main.h))
		end
	end
	Visible.Notify()
end

---------------------------------------------------------------------------
-- Events and hooks
---------------------------------------------------------------------------

-- Start (from Core.lua after ADDON_LOADED); applied afterwards via ns.ApplyGeometry.
-- From here on qnCore.Visible uses the area on the monitors.
function Layout.Init()
	Visible.SetAreaProvider(Layout.GetVisibleAbs)
	ns.events.Register("PLAYER_ENTERING_WORLD", Visible.Notify)
	-- Blizzard puts UIParent back across the whole window here (at the top only offset by notch/debug bars)
	hooksecurefunc("UpdateUIParentPosition", ReapplyUI)
end

---------------------------------------------------------------------------
-- Slash: /qnvp monitors | check
---------------------------------------------------------------------------

function Layout.Describe()
	local lines = {}
	local data = Layout.GetData()
	if not data then
		lines[1] = "|cffff8080" .. (problem or L["No monitor data."]) .. "|r"
		return lines
	end
	for _, m in ipairs(data.monitors) do
		lines[#lines + 1] = ("%d: %s  x %d, y %d, %d × %d%s%s"):format(m.index, m.name or m.device or "?",
			m.x, m.y, m.w, m.h, m == data.main and ("  |cff80ff80%s|r"):format(L["Main monitor"]) or "",
			m.selected == false and ("  (%s)"):format(L["not selected, but shows part of the window"]) or "")
	end
	if not DB().useMonitorData then
		lines[#lines + 1] = "|cffffff80" .. L["Monitor data is turned off (options, Second Monitor)."] .. "|r"
	end
	return lines
end

function Layout.Slash(cmd)
	if cmd == "monitors" then
		ns.Print((constrained and L["Game window %d × %d, interface on the main monitor:"]
			or L["Game window %d × %d, interface across the whole window:"]):format(ns.screen[1], ns.screen[2]))
		for _, line in ipairs(Layout.Describe()) do
			ns.Print(line)
		end
		return true
	elseif cmd == "check" then
		Layout.Report()
		return true
	end
	return false
end

-- Short description of a check result
function Layout.DescribeEntry(e)
	local where = e.visible < 0.0001 and ("|cffff6060%s|r"):format(L["fully outside"])
		or L["|cffffd060partly outside|r (%d %% visible)"]:format(math.floor(e.visible * 100))
	local notes = { e.source }
	if e.editMode then notes[#notes + 1] = HUD_EDIT_MODE_MENU end
	if e.protected then notes[#notes + 1] = L["protected"] end
	return where, table.concat(notes, ", ")
end

-- Reports frames outside the monitors in chat (/qnvp check). Moves nothing.
function Layout.Report()
	local list = Layout.CheckFrames()
	if #list == 0 then
		ns.Print(L["All visible interface elements are on a monitor."])
	end
	for _, e in ipairs(list) do
		local where, notes = Layout.DescribeEntry(e)
		ns.Print(("|cffffff80%s|r – %s – %s"):format(e.name, where, notes))
	end
	if #list > 0 then
		ns.Print(L["Move them one at a time: Options → qnViewPort → Monitors."])
	end
end
