-- Scenario 2: qnViewPort – on events apply the viewport only clamped (do not save),
-- save on input, confirmation period, mapFade, map at login, dual monitor messages,
-- bags via UpdateContainerFrameAnchors, combat lockdown.

-- additions to the stub (before LoadAddon)
local T = 1000
GetTime = function() return T end
C_CVar.GetCVarDefault = function(k) return ({ mapFade = "1" })[k] end
WorldFrame.IsProtected = function() return true end   -- protected as in the client: combat lockdown applies
local toggles = 0
ToggleWorldMap = function() toggles = toggles + 1 end
WorldMapFrame = CreateFrame("Frame", "WorldMapFrame")
WorldMapFrame:Hide()
function WorldMapFrame:SetMapID(id) self.mapID = id end
local winW, winH = 5760, 2160
-- monitor data as generated by scripts\Initialize-WowMonitors.ps1
qnViewPortMonitors = { window = { x = 0, y = 0, width = 5760, height = 2160 }, monitors = {
	{ x = 0, y = 0, width = 3840, height = 2160, main = true, selected = true },
	{ x = 3840, y = 377, width = 1920, height = 1200, selected = true },
} }
C_VideoOptions.GetCurrentGameWindowSize = function() return { x = winW, y = winH } end
local CHAT = {}
function DEFAULT_CHAT_FRAME:AddMessage(msg) CHAT[#CHAT + 1] = tostring(msg) end
local checks, boxes, drops = {}, {}, {}
local origCreateFrame = CreateFrame
function CreateFrame(kind, name, parent, template)
	local f = origCreateFrame(kind, name, parent, template)
	if template == "UICheckButtonTemplate" then checks[#checks + 1] = f end
	if template == "InputBoxTemplate" then boxes[#boxes + 1] = f end
	if template == "WowStyle1DropdownTemplate" then drops[#drops + 1] = f end
	return f
end

-- saved: left 3000 pixels (more than half the window width), without monitor data
qnCoreCharDB = { layout = "account:Raid" }
qnViewPortDB = { profiles = { ["account:Raid"] = { viewport = { 3000, 0, 0, 0 }, dual = { useMonitorData = false } } }, global = {} }

LoadAddon("qnCore")
local vp = LoadAddon("qnViewPort")
local L = vp.L
FireEvent("PLAYER_LOGIN")
FireEvent("PLAYER_ENTERING_WORLD", true, false)
RunTimers()
SetEditModeLayout(3)

-- left offset of WorldFrame in screen pixels
local function WFLeft()
	local ux = vp.UnitsPerPixel()
	return math.floor(WorldFrame._points[1][2] / ux + 0.5)
end
local function Count(key)
	local n = 0
	for _, m in ipairs(CHAT) do if m:find(L[key], 1, true) then n = n + 1 end end
	return n
end
-- checkbox whose check mark follows vp.db.dual[key] on refresh (also via getter)
local function CheckBox(key)
	local d = vp.db.dual
	local old, found = d[key], nil
	for _, cb in ipairs(checks) do
		if not found and rawget(cb, "Refresh") then
			d[key] = true cb:Refresh() local on = cb._checked
			d[key] = false cb:Refresh() local off = cb._checked
			if on == true and not off then found = cb end
		end
	end
	d[key] = old
	if found then found:Refresh() end
	return found
end
local function Click(cb, on)
	cb:SetChecked(on)
	cb:GetScript("OnClick")(cb)
	RunTimers()
end

-- 1. load: apply clamped, keep the saved value
Check(vp.db.viewport[1] == 3000, "load: saved value stays 3000: " .. vp.db.viewport[1])
Check(vp.GetViewport()[1] == 2880 and WFLeft() == 2880, "load: applied clamped to 2880: " .. WFLeft())

-- 2. window size: apply clamped, do not save
winW, winH = 4000, 2000
FireEvent("DISPLAY_SIZE_CHANGED") RunTimers()
Check(vp.GetViewport()[1] == 2000 and vp.db.viewport[1] == 3000, "smaller window: 2000 applied, 3000 saved")
winW, winH = 5760, 2160
FireEvent("DISPLAY_SIZE_CHANGED") RunTimers()
Check(vp.GetViewport()[1] == 2880 and vp.db.viewport[1] == 3000, "window large again: 2880 applied, 3000 saved")

-- 3. Blizzard resets WorldFrame: the applied value is restored
WorldFrame._points = {}
WorldFrame:SetAllPoints()
Check(WorldFrame._points[1] and WFLeft() == 2880, "hook on WorldFrame restores the clamped viewport")

-- 4. profile switch: new profile = copy, applied clamped, nothing saved
SetEditModeLayout(4)
Check(vp.db ~= qnViewPortDB.profiles["account:Raid"] and vp.db.viewport[1] == 3000 and vp.GetViewport()[1] == 2880,
	"profile switch: copy keeps 3000, applied 2880")
SetEditModeLayout(3)

-- 5. player input saves; without confirmation the previously saved value is written back
SlashCmdList.QNVIEWPORT("100 0 0 0")
Check(vp.db.viewport[1] == 100 and WFLeft() == 100, "/qnvp 100 0 0 0 saves and applies")
T = T + 21
RunTickers()
Check(vp.db.viewport[1] == 3000 and vp.GetViewport()[1] == 2880 and Count("Setting not confirmed – previous viewport restored.") == 1,
	"after 20 s without confirmation: saved value 3000 restored unchanged")
SlashCmdList.QNVIEWPORT("0 0 0 0")
Check(vp.db.viewport[1] == 0 and not vp.IsActive(), "/qnvp 0 0 0 0 saves immediately")

-- 6. mapFade: on remembers the value, off writes it back
local cFade = CheckBox("mapNoFade")
Check(cFade ~= nil, "checkbox mapNoFade found")
C_CVar._v.mapFade = "1"
Click(cFade, true)
Check(C_CVar._v.mapFade == "0" and qnViewPortDB.global.mapFadeSaved == "1", "mapNoFade on: mapFade 0, previous 1 remembered account-wide")
FireEvent("PLAYER_ENTERING_WORLD", false, false) RunTimers()
Check(C_CVar._v.mapFade == "0" and qnViewPortDB.global.mapFadeSaved == "1", "loading screen: stays 0, remembered value stays")
Click(cFade, false)
Check(C_CVar._v.mapFade == "1" and qnViewPortDB.global.mapFadeSaved == nil, "mapNoFade off: 1 restored")
C_CVar._v.mapFade = "0"   -- set by the player in Blizzard's options
FireEvent("PLAYER_ENTERING_WORLD", false, false) RunTimers()
Check(C_CVar._v.mapFade == "0", "mapNoFade off: CVar is not touched otherwise")
Click(cFade, true)
Click(cFade, false)
Check(C_CVar._v.mapFade == "1", "without remembered value: Blizzard's default when switching off")

-- 7. open the map only at login or /reload; zone change with the map open
vp.db.dual.mapAutoOpen = true
toggles = 0
FireEvent("PLAYER_ENTERING_WORLD", false, false) RunTimers()
Check(toggles == 0, "loading screen: map not opened")
FireEvent("PLAYER_ENTERING_WORLD", true, false) RunTimers()
Check(toggles == 1, "login: map opened")
FireEvent("PLAYER_ENTERING_WORLD", false, true) RunTimers()
Check(toggles == 2, "/reload: map opened")
Check(WorldMapFrame:GetScript("OnShow") == nil, "no own OnShow hook on the world map")
WorldMapFrame:Show()
FireEvent("ZONE_CHANGED_NEW_AREA") RunTimers()
Check(WorldMapFrame.mapID == 1, "zone change with the map open: map of the zone")

-- 8. dual monitor mode: message only when actually switching
CHAT = {}
SlashCmdList.QNVIEWPORT("dual on") RunTimers()
Check(Count("Dual monitor mode on: 3D world on the main monitor.") == 1, "dual on: one message")
Check(vp.db.dual.enabled and vp.db.viewport[2] == 1920 and vp.db.viewport[1] == 0, "dual on: viewport saved to the main monitor")
SlashCmdList.QNVIEWPORT("dual on") RunTimers()
SlashCmdList.QNVIEWPORT("dual right") RunTimers()
-- "Dual monitor mode active": check mark follows dual.enabled
local enable = CheckBox("enabled")
Check(enable ~= nil, "dual monitor mode checkbox found")
Click(enable, true)
Check(Count("Dual monitor mode on: 3D world on the main monitor.") == 1, "on again / side / checkbox: no further message (" .. #CHAT .. ")")
SlashCmdList.QNVIEWPORT("dual 1600 1200") RunTimers()
Check(vp.db.viewport[2] == 1600 and Count("Dual monitor mode on: 3D world on the main monitor.") == 1, "new size: viewport updated, without message")
Click(enable, false)
Check(not vp.db.dual.enabled and vp.db.viewport[2] == 0 and Count("Dual monitor mode off.") == 1, "checkbox off: one message, viewport back")
SlashCmdList.QNVIEWPORT("200 0 0 0")
vp.EndKeep()
SlashCmdList.QNVIEWPORT("dual off") RunTimers()
Check(Count("Dual monitor mode off.") == 1 and vp.db.viewport[1] == 200, "dual off with mode already off: no message, viewport stays")

-- 9. bags via the hook on UpdateContainerFrameAnchors
local bag = CreateFrame("Frame", "ContainerFrame1")
bag:Show()
UpdateContainerFrameAnchors() RunTimers()
Check(bag._points == nil, "without option: bags stay")
vp.db.dual.bags = true
ToggleBackpack() RunTimers()
Check(bag._points == nil, "ToggleBackpack is no longer hooked")
UpdateContainerFrameAnchors() RunTimers()
local p = bag._points and bag._points[1]
Check(p and p[1] == "BOTTOMRIGHT" and p[2].qnViewPortIgnore and p[3] == "BOTTOMRIGHT", "bag at the corner of the area")

-- 10. combat lockdown
bag._points = nil
bag.IsProtected = function() return true end
QN_COMBAT = true
UpdateContainerFrameAnchors() RunTimers()
Check(bag._points == nil, "combat: protected bag is not moved")
SlashCmdList.QNVIEWPORT("0 0 0 0")
Check(vp.db.viewport[1] == 0 and WFLeft() == 200, "combat: saved, WorldFrame unchanged")
QN_COMBAT = false
FireEvent("PLAYER_REGEN_ENABLED") RunTimers()
Check(WFLeft() == 0, "applied after combat")

-- 11. refresh the "Second monitor" options page: manual values or measured, locked values
local function Box(key) for _, b in ipairs(boxes) do if b.key == key then return b end end end
local function Record(w)
	rawset(w, "SetEnabled", function(self, on) self._enabled = on end)
	if rawget(w, "label") then
		rawset(w.label, "SetFontObject", function(self, font) self._font = font end)
	end
end
for _, b in ipairs(boxes) do Record(b) end
local side
for _, dd in ipairs(drops) do
	Record(dd)
	for _, r in ipairs(dd._radios or {}) do
		if r.text == L["Left of the main monitor"] then side = dd end
	end
end
local wBox, hBox, yBox = Box("width"), Box("height"), Box("offsetY")
Check(wBox and hBox and yBox and side, "fields and side selection found")
vp.db.dual.width, vp.db.dual.height, vp.db.dual.offsetY, vp.db.dual.side = 1600, 1000, 50, "RIGHT"
vp.db.dual.mapFollowZone = true
vp.Dual.RefreshOptions()
Check(wBox._text == 1600 and hBox._text == 1000 and yBox._text == 50, ("without monitor data: manual values %s/%s/%s"):format(
	tostring(wBox._text), tostring(hBox._text), tostring(yBox._text)))
Check(wBox._enabled == true and wBox.label._font == "GameFontHighlight", "without monitor data: field usable")
Check(side._enabled == true and side.label._font == "GameFontHighlight" and side._text == L["Right of the main monitor"],
	"without monitor data: side usable: " .. tostring(side._text))
Check(CheckBox("mapFollowZone")._checked == true and not CheckBox("mapNoFade")._checked, ("checkboxes from DB: %s/%s"):format(
	tostring(CheckBox("mapFollowZone")._checked), tostring(CheckBox("mapNoFade")._checked)))
local bx = Box("bagsOffsetX")
vp.db.dual.bagsOffsetX = 12
vp.Dual.RefreshOptions()
Check(bx and bx._text == 12 and bx._enabled == nil, "bag offset: value, not locked")
vp.db.dual.useMonitorData = true
vp.Dual.RefreshOptions()
Check(wBox._text == 1920 and hBox._text == 1200 and yBox._text == 377, ("monitor data: measured values %s/%s/%s"):format(
	tostring(wBox._text), tostring(hBox._text), tostring(yBox._text)))
Check(wBox._enabled == false and yBox.label._font == "GameFontDisable", "monitor data: fields locked")
Check(side._enabled == false and side.label._font == "GameFontDisable", "monitor data: side locked")
Check(vp.db.dual.width == 1600, "monitor data: manual value stays saved")
vp.db.dual.useMonitorData = false
vp.Dual.RefreshOptions()
Check(wBox._text == 1600 and wBox._enabled == true, "without monitor data again: manual value")

print(FAILS and ("FAILED: " .. FAILS) or "all checks passed")
